# Generated by Django 3.1.4 on 2020-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('stock_amount', models.IntegerField()),
                ('featured', models.BooleanField(default=False)),
                ('amount_sold', models.IntegerField(default=0)),
                ('company', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=14)),
                ('password', models.CharField(max_length=255)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
